
---
- name: Tunnel S3 Data to Fleet
  hosts: all
  gather_facts: no
  tasks:
    # --- TASK 1: Ensure the directory exists on the VEHICLE ---
    - name: Create downloads folder
      ansible.builtin.file:
        path: /home/ubuntu/downloads
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    # --- TASK 2: Ensure AWS CLI is installed on the RUNNER ---
    - name: Ensure AWS CLI is installed (Alpine/Docker)
      community.general.apk:
        name: 
          - aws-cli
          - pv
        state: present
        update_cache: yes
      delegate_to: localhost
      ignore_errors: yes 

    # --- TASK 3: Stream the file ---
    - name: Stream file through EC2 tunnel
      ansible.builtin.shell:
        cmd: "./fetch_s3.sh {{ file_name }} {{ inventory_hostname }} /home/ubuntu/downloads/{{ file_name }}"
        chdir: "{{ playbook_dir }}"
      register: s3_output
      delegate_to: localhost
      throttle: 1

    # --- TASK 4: Show Transfer Speed ---
    - name: Show Transfer Speed
      debug:
        var: s3_output.stderr_lines
